    assert isinstance(tag, GTMTag)

    assert tag.paused == tag_get.get("paused")
    assert tag.setupTag == tag_get.get("setupTag")
    assert tag.firingRuleId == tag_get.get("firingRuleId", [])
    assert tag.accountId == tag_get.get("accountId")
    assert tag.teardownTag == tag_get.get("teardownTag")
    assert tag.priority == tag_get.get("priority")
    assert tag.workspaceId == tag_get.get("workspaceId")
    assert tag.parentFolderId == tag_get.get("parentFolderId")
    assert tag.scheduleStartMs == tag_get.get("scheduleStartMs")
    assert tag.scheduleEndMs == tag_get.get("scheduleEndMs")
    assert tag.containerId == tag_get.get("containerId")
    assert tag.tagFiringOption == tag_get.get("tagFiringOption")
    assert tag.tagId == tag_get.get("tagId")
    assert tag.blockingRuleId == tag_get.get("blockingRuleId", [])
    assert tag.tagManagerUrl == tag_get.get("tagManagerUrl")
    assert tag.fingerprint == tag_get.get("fingerprint")
    assert tag.firingTriggerId == tag_get.get("firingTriggerId", [])
    assert tag.name == tag_get.get("name")
    assert tag.type == tag_get.get("type")
    assert tag.notes == tag_get.get("notes")
    assert tag.liveOnly == tag_get.get("liveOnly")
    assert tag.blockingTriggerId == tag_get.get("blockingTriggerId", [])
    assert tag.path == tag_get.get("path")

    assert isinstance(tag.parameter[0], GTMParameter)